name: build-artifact

on:
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Replace secret placeholders
      run: |
        sed -i "s/PHONE-REDACT/${{ secrets.PHONE_NUMBER }}/g" resume.tex
        sed -i "s/EMAIL-REDACT/${{ secrets.EMAIL_ADDRESS }}/g" resume.tex

    - name: Compile latex
      uses: xu-cheng/latex-action@v4
      with:
        root_file: resume.tex

    - name: Rename PDF with git SHA
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
        DATE=$(date +'%y%m%d')
        mv resume.pdf "resume-${DATE}-${SHORT_SHA}.pdf"

    - name: Upload PDF as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume-*.pdf
